version: '3'

services: 
  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports: 
      - 27017:27017
  
  fireplace:
    image: dormao/fireplace:1.1.1
    environment:
      MONGO_URL: 'mongodb://user:password@mongo:27017'
      SERVER_ADDRESS: ':8999'
    ports:
      - 8999:8999
    